### ISSUE TITLE
Graph is very pointy

### ISSUE THREAD

**Issue by simonszu** [DennisOSRM/hms-mqtt-publisher#112]
I am using this project as anyone else, but am also exporting Home Assistant data via Prometheus and graphing it via Grafana. It seems that the grafana graph is quite pointy with lots of spikes. 
![Screenshot 2024-03-23 at 13 18 39](https://github.com/DennisOSRM/hms-mqtt-publisher/assets/700707/cc260865-cc17-4a26-912f-1a8792589750)

I am not sure if this is usual for balcony solar devices, since the sun isn't rapidly switching on and off, so i am opening this issue to confirm if this is the usual behaviour for the metric, or if there is something to be improved.

**Comment by dominikandreas** [comment]
The spikes are typical for a day with a mix of sun and clouds. For straight and continuous sunshine, this should not happen.

For comparison, here's one of mine from last Thursday:
![Screenshot_20240323-133433](https://github.com/DennisOSRM/hms-mqtt-publisher/assets/13525040/85013a4e-368a-4ce8-aec3-fe4500cb49a0)

**Comment by DennisOSRM** [comment]
Seems like the panels were obstructed some of the time, perhaps? What does the underlying data say?

**Comment by simonszu** [comment]
The underlying data looks also quite spiky, but without any gaps (which are showing up in grafana when zoomed in). The same sensor as a dashboard card in Home Assistant looks similar to @dominikandreas but with smaller amplitude, which is caused by my installation form.
