### ISSUE TITLE
Set MQTT Port as a Configurable Parameter

### ISSUE THREAD

**Issue by ringelbaer** [DennisOSRM/hms-mqtt-publisher#12]
Hello,

I've noticed that the MQTT port is currently hardcoded in the application. For improved flexibility and to accommodate various deployment environments, it would be beneficial to have the MQTT port settable through a configuration parameter.

Thanks

**Comment by DennisOSRM** [comment]
Implemted in 6fe78e6d3bdfcf70f12a959629a9cf0f8135902e.
