### ISSUE TITLE
MQTT server without authentication

### ISSUE THREAD

**Issue by cph0x00** [DennisOSRM/hms-mqtt-publisher#51]
Since Docker v0.2 there seem to be username und password required arguments for the MQTT server connection. The container crashes while starting if I don't provide any user credentials. But I cannot provide correct user credentials as my MQTT server has no authentication requirements.

**Comment by DennisOSRM** [comment]
Hey, thanks for the report. This has been fixed in main branch recently. It will be part of the upcoming release.

**Comment by cph0x00** [comment]
excellent. thanks!
